### PR TITLE
Remove bin/bean-query from the repository

### PR DESCRIPTION
**Pull request by dnicolodi**
The executable is created by setuptools on install and alternatively
the tool can be run from the source directory with 'python -m beanquery'.

### CODE REVIEW

**Comment by dnicolodi** [comment]
@blais Does the alias trick work for you?

**Comment by blais** [comment]
Haven't been able to pay attention yet

**Comment by blais** [comment]
Hmm, I like the executable because it allows us to run in development mode.
Like... I *never* install beancount or related projects, I just run from the checkouts.
Without that, I'd have to create some alias, I'm not sure what's the benefit of removing the script.

**Comment by dnicolodi** [comment]
I run stuff from Python virtual environments where the packages are installed in development mode with `python setup.py develop`. In this way all dependencies are contained in the virtual env and I can run stuff with contradicting dependencies. 

I put an alias for you in the `etc/env` file. I don't know how you pull the definitions in that file into your environment, but I was hoping that this is all what is required to be able to keep using `bean-query` without the explicit script in `bin/`.

The issue is that the directory layout I use for development is to have the root of the venv and the root of the git checkout to be the same directory. This works well but the `bin/bean-query` is shipped in the repo, overwritten by a generated scirpt when the beancount dependency is installed, and overwritten again when beanquery is installed in development mode. However, with later git checkouts or beancount package update the file has the wrong content. Less annoyingly, it also always shows up as modified in the git status.

Not a big deal as I retrained my muscle memory to always use `python -m beanquery` instead that the plain `bean-query` but I though it was worth to give it a try to fix this little annoyance. The level of annoyance halves if we remove the `bean-query` script from the beancount package.

**Comment by dnicolodi** [comment]
This is only a minor nuisance in my development workflow which does not warrant breaking someone else workflow. Let's keep the script.

**Pull request closed without merging**
