### PR TITLE
Use pipenv to manage the dependencies.

### PR DESCRIPTION
**Pull request by doriath**
I am thinking about using pipenv for local development of beanquery, as
it will allow me to isolate the dependencies from my system packages (I
am still using beancount-v2 for my ledger, but some packages I am
working on like this beanquery requires beancount-v3).

### CODE REVIEW

**Comment by doriath** [comment]
Please let me know what you think about pipenv. I am still pretty new to python, but it looks like a pretty nice way to isolate the development from system dependencies and maybe will make it more reproducible. WDYT?

**Comment by dnicolodi** [comment]
The use of pipenv (or something else of similar fashion) should be a local decision, with the support files not committed to the repo.

**Comment by doriath** [comment]
That sounds good, what do you think about adding `Pipfile` and `Pipfile.lock` to `.gitignore`?

**Comment by dnicolodi** [comment]
My usual policy for `.gitignore` is to have in there only files that are created by the project itself (like temp files, build artifacts, etc...) and keep all others in my local git configuration. In this case, as you most likely never want to commit these to any repo, you can add 'Pipfile' and 'Pipfile.lock` to your use git config ignore (I forgot where in `~/.git` it is).

**Comment by doriath** [comment]
Ah, that is a good idea, thanks! Closing this PR.

**Pull request closed without merging**
