### PR TITLE
Add #prices table definition

### LINKED ISSUE #118: show prices?  `SELECT * from #prices`
What do you think of add `#prices`?

I'm not getting the result I except from `VALUE()` and looking at the price database would be useful.

### PR DESCRIPTION
**Pull request by dnicolodi**
Fixes #118.

### CODE REVIEW

**Comment by dnicolodi** [comment]
This is a bit rough on the edges but functional. In particular `select * from #prices` returns a `meta` column that could benefit from a better presentation in the query results render.

**Comment by dnicolodi** [comment]
This looks a better now. However, it still only outputs prices from explicit `price` directives in the ledger. Reading #118 again, I have the impression that what is desired is actually a table with the in-memory price database with entries also for the prices derived from postings with price information. @tbm is this the case?

**Comment by tbm** [comment]
Yes, but wouldn't `beancount.plugins.auto_accounts` take care of that automatically?

**Comment by dnicolodi** [comment]
`beancount.plugins.auto_accounts` inserts `open` directives` for accounts that are not explicitly open, it does not insert `price` directives.

**Comment by tbm** [comment]
Sorry, I copied the wrong line from my config without looking.  I meant `beancount.plugins.implicit_prices`.  I think that addresses your original comment, or did I misunderstand your question?

**Comment by dnicolodi** [comment]
Nice, I never used that plugin and I didn't know of its existence. I wonder if beanquery should do the equivalent operation when instantiating the `prices` table instead than relying on the plugin.

**Comment by tbm** [comment]
I think you should just query the price db and let users decide if they want to enable `beancount.plugins.implicit_prices` or not.

**Comment by blais** [comment]
+1

**Pull request merged**
