### PR TITLE
Add packaging

### PR DESCRIPTION
**Pull request by dnicolodi**
@blais Does removing the bin/bean-query executable get in the way of your workflow?

### CODE REVIEW

**Comment by blais** [comment]
Why remove bean-query?

**Comment by dnicolodi** [comment]
It is only removed from the source directory, it is created by setuptools on install or develop. My standard workflow to work on the package is something like:
```
git clone git@github.com:beancount/beanquery.git
cd beanquery
python -m venv .
bin/python setup.py develop
```
which (with the additions in this PR) creates `bin/bean-query`. Having a file with the same name in the repo is a bit annoying as git continuously complains about it when I switch branches. I can workaround this cloning the repo in a `src` subdirectory but I like the flat structure.

**Comment by blais** [comment]
Hmm, okay, but then during development, how do I run it?

**Comment by blais** [comment]
I never install things... I just git co and setup my paths.

**Comment by dnicolodi** [comment]
`python setup.py develop` (in a somehow simplified view) installs a "link" to the source directory into the python module path (which can be a virtual environment or not). You can see it as equivalent to adding the path to PYTHONPATH.

**Comment by dnicolodi** [comment]
I dropped the removal of `bin/bean-query` from the repository and merged the packaging work. I'll open a separate PR for that.

**Pull request merged**
